version: '3'

services:
  superset:
    image: amancevice/superset
    environment:
      - SUPERSET_LOAD_EXAMPLES=yes
      - SUPERSET_ADMIN_USERNAME=admin
      - SUPERSET_ADMIN_PASSWORD=superset
    ports:
      - "8088:8088"
    depends_on:
      - db
    command: >
      sh -c "superset db upgrade && superset init"
    volumes:
      - "./superset:/home/superset/.superset"

  db:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=superset
      - POSTGRES_USER=superset
      - POSTGRES_DB=superset
    volumes:
      - ./postgres-data:/var/lib/postgresql/data